# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44c451660ff94986949ecad7eeafbc27d7542aa68576ce34cc942d30a37791c927b6bc6f8d12dfe723b8bbd166301c9c731fc4e4f4d4be98691cf23f959dd8cf

test:
  secret_key_base: d5aabdca73bf10211efe1ba06fd8402d3566c48ef560b1738b0c0cb3f01a29c9ac2ec09532c16e3f903857aebfec906af96a114290816bcdd03ee7005077fbe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
